//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettingsLabel {
            get {
                return ResourceManager.GetString("AccountSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible.
        /// </summary>
        public static string ActionIrreversible {
            get {
                return ResourceManager.GetString("ActionIrreversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string AddItemLabel {
            get {
                return ResourceManager.GetString("AddItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add label.
        /// </summary>
        public static string AddLabelLabel {
            get {
                return ResourceManager.GetString("AddLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string AddNewItemLabel {
            get {
                return ResourceManager.GetString("AddNewItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose project first!.
        /// </summary>
        public static string ChooseProjectFirstPopup {
            get {
                return ResourceManager.GetString("ChooseProjectFirstPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to DELETE your account?.
        /// </summary>
        public static string ConfirmAccountDelete {
            get {
                return ResourceManager.GetString("ConfirmAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update your information?.
        /// </summary>
        public static string ConfirmInfoChanges {
            get {
                return ResourceManager.GetString("ConfirmInfoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update your issue?.
        /// </summary>
        public static string ConfirmIssueChanges {
            get {
                return ResourceManager.GetString("ConfirmIssueChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to DELETE your issue?.
        /// </summary>
        public static string ConfirmIssueDelete {
            get {
                return ResourceManager.GetString("ConfirmIssueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string ConfirmLogOut {
            get {
                return ResourceManager.GetString("ConfirmLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update your password?.
        /// </summary>
        public static string ConfirmPasswordChanges {
            get {
                return ResourceManager.GetString("ConfirmPasswordChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update your project?.
        /// </summary>
        public static string ConfirmProjectChanges {
            get {
                return ResourceManager.GetString("ConfirmProjectChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to DELETE your project?.
        /// </summary>
        public static string ConfirmProjectDelete {
            get {
                return ResourceManager.GetString("ConfirmProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection completed successfully.
        /// </summary>
        public static string ConnectionCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ConnectionCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection completed unsuccessfully. Try again.
        /// </summary>
        public static string ConnectionCompletedUnsuccessfully {
            get {
                return ResourceManager.GetString("ConnectionCompletedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to connect to the database. Check the connection string..
        /// </summary>
        public static string ConnectionStringExeption {
            get {
                return ResourceManager.GetString("ConnectionStringExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created item must have a name!.
        /// </summary>
        public static string CreatedItemNamePopup {
            get {
                return ResourceManager.GetString("CreatedItemNamePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger Zone.
        /// </summary>
        public static string DangerZoneLabel {
            get {
                return ResourceManager.GetString("DangerZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete your account.
        /// </summary>
        public static string DeleteAccountLabel {
            get {
                return ResourceManager.GetString("DeleteAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string DescriptionOptionalLabel {
            get {
                return ResourceManager.GetString("DescriptionOptionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneStatus {
            get {
                return ResourceManager.GetString("DoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new connection string:.
        /// </summary>
        public static string EnterNewString {
            get {
                return ResourceManager.GetString("EnterNewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and hope you have a good day!.
        /// </summary>
        public static string GoodDay {
            get {
                return ResourceManager.GetString("GoodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgressStatus {
            get {
                return ResourceManager.GetString("InProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database connection string.
        /// </summary>
        public static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string IssueLabel {
            get {
                return ResourceManager.GetString("IssueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue with that name already exists in selected project!.
        /// </summary>
        public static string IssueNameOccupiedPopup {
            get {
                return ResourceManager.GetString("IssueNameOccupiedPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string IssuesLabel {
            get {
                return ResourceManager.GetString("IssuesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your issue has been updated.
        /// </summary>
        public static string IssueUpdated {
            get {
                return ResourceManager.GetString("IssueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string LabelsLabel {
            get {
                return ResourceManager.GetString("LabelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string LetGetStarted {
            get {
                return ResourceManager.GetString("LetGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already occupied. Try another one.
        /// </summary>
        public static string LoginOccupiedPopup {
            get {
                return ResourceManager.GetString("LoginOccupiedPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out of your account.
        /// </summary>
        public static string LogOutLabel {
            get {
                return ResourceManager.GetString("LogOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumPriority {
            get {
                return ResourceManager.GetString("MediumPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of item.
        /// </summary>
        public static string NameOfItemLabel {
            get {
                return ResourceManager.GetString("NameOfItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comment provided.
        /// </summary>
        public static string NoCommentProvided {
            get {
                return ResourceManager.GetString("NoCommentProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description provided.
        /// </summary>
        public static string NoDescriptionProvided {
            get {
                return ResourceManager.GetString("NoDescriptionProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t changed the issue!.
        /// </summary>
        public static string NotChangedIssuePopup {
            get {
                return ResourceManager.GetString("NotChangedIssuePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not changed your personal information!.
        /// </summary>
        public static string NotChangedPersonalInfoPopup {
            get {
                return ResourceManager.GetString("NotChangedPersonalInfoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t changed the project!.
        /// </summary>
        public static string NotChangedProjectPopup {
            get {
                return ResourceManager.GetString("NotChangedProjectPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is too short. It should be more than 8 symbols.
        /// </summary>
        public static string PasswordIsTooShortPopup {
            get {
                return ResourceManager.GetString("PasswordIsTooShortPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords you entered are not equal! Try again.
        /// </summary>
        public static string PasswordNotEqualPopup {
            get {
                return ResourceManager.GetString("PasswordNotEqualPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformationLabel {
            get {
                return ResourceManager.GetString("PersonalInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal information has been updated.
        /// </summary>
        public static string PersonalInfoUpdated {
            get {
                return ResourceManager.GetString("PersonalInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityLabel {
            get {
                return ResourceManager.GetString("PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectLabel {
            get {
                return ResourceManager.GetString("ProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with that name already exists!.
        /// </summary>
        public static string ProjectNameOccupiedPopup {
            get {
                return ResourceManager.GetString("ProjectNameOccupiedPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsLabel {
            get {
                return ResourceManager.GetString("ProjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project has been updated.
        /// </summary>
        public static string ProjectUpdated {
            get {
                return ResourceManager.GetString("ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnection to database....
        /// </summary>
        public static string ReconnectionToDatabase {
            get {
                return ResourceManager.GetString("ReconnectionToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Create it!.
        /// </summary>
        public static string RegistrationHyperlink {
            get {
                return ResourceManager.GetString("RegistrationHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ReviewStatus {
            get {
                return ResourceManager.GetString("ReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project.
        /// </summary>
        public static string SelectProjectLabel {
            get {
                return ResourceManager.GetString("SelectProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignupButton {
            get {
                return ResourceManager.GetString("SignupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is.
        /// </summary>
        public static string TodayIs {
            get {
                return ResourceManager.GetString("TodayIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        public static string ToDoStatus {
            get {
                return ResourceManager.GetString("ToDoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of item.
        /// </summary>
        public static string TypeOfItemLabel {
            get {
                return ResourceManager.GetString("TypeOfItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password! Try again.
        /// </summary>
        public static string WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
            }
        }
    }
}
